import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Briefcase, Plus, Search } from 'lucide-react';
import { Badge, Button, Card, CardBody, EmptyState, Input, Skeleton } from '@/components/ui';
import { listJobs } from '@/api/jobs';
import { relativeTime } from '@/lib/format';
export default function JobsList() {
    const [jobs, setJobs] = useState(null);
    const [q, setQ] = useState('');
    useEffect(() => { listJobs().then(setJobs).catch(() => setJobs([])); }, []);
    const filtered = (jobs || []).filter((j) => !q || j.title.toLowerCase().includes(q.toLowerCase()) || (j.location || '').toLowerCase().includes(q.toLowerCase()));
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-semibold", children: "Jobs" }), _jsx("p", { className: "text-sm text-subtle mt-1", children: "All your job postings." })] }), _jsx(Link, { to: "/app/jobs/new", children: _jsx(Button, { iconLeft: _jsx(Plus, { className: "h-4 w-4" }), children: "New job" }) })] }), _jsxs("div", { className: "relative max-w-sm", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-subtle" }), _jsx(Input, { value: q, onChange: (e) => setQ(e.target.value), placeholder: "Search title or location...", className: "pl-9" })] }), jobs === null ? (_jsxs("div", { className: "grid md:grid-cols-2 gap-4", children: [_jsx(Skeleton, { className: "h-28" }), _jsx(Skeleton, { className: "h-28" })] })) : filtered.length === 0 ? (_jsx(Card, { children: _jsx(CardBody, { children: _jsx(EmptyState, { icon: _jsx(Briefcase, { className: "h-6 w-6" }), title: q ? 'No jobs match your search' : 'No jobs yet', description: q ? 'Try a different keyword.' : 'Create your first job posting to start screening candidates.', action: !q && _jsx(Link, { to: "/app/jobs/new", children: _jsx(Button, { iconLeft: _jsx(Plus, { className: "h-4 w-4" }), children: "Create job" }) }) }) }) })) : (_jsx("div", { className: "grid md:grid-cols-2 gap-4", children: filtered.map((j) => (_jsx(Link, { to: `/app/jobs/${j.id}`, children: _jsx(Card, { hover: true, className: "h-full", children: _jsxs(CardBody, { children: [_jsxs("div", { className: "flex items-start justify-between gap-2", children: [_jsx("h3", { className: "font-semibold", children: j.title }), _jsx(Badge, { tone: j.status === 'OPEN' ? 'green' : 'gray', children: j.status })] }), _jsxs("div", { className: "mt-2 text-xs text-subtle flex flex-wrap gap-2 items-center", children: [j.seniority && _jsx(Badge, { tone: "violet", children: j.seniority }), j.location && _jsx("span", { children: j.location }), j.employmentType && _jsxs("span", { children: ["\u00B7 ", j.employmentType] })] }), _jsx("p", { className: "mt-3 text-sm text-fg/80 line-clamp-2", children: j.description }), _jsxs("div", { className: "mt-3 text-xs text-subtle", children: ["Updated ", relativeTime(j.updatedAt)] })] }) }) }, j.id))) }))] }));
}
