import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardBody, CardHeader } from '@/components/ui';
import { useAuth } from '@/store/auth';
import { useTheme } from '@/store/theme';
export default function Settings() {
    const { user } = useAuth();
    const { theme, toggle } = useTheme();
    return (_jsxs("div", { className: "space-y-6 max-w-3xl", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-semibold", children: "Settings" }), _jsx("p", { className: "text-sm text-subtle mt-1", children: "Account, appearance, and integrations." })] }), _jsxs(Card, { children: [_jsx(CardHeader, { title: "Profile" }), _jsxs(CardBody, { className: "space-y-2 text-sm", children: [_jsx(Row, { label: "Full name", value: user?.fullName }), _jsx(Row, { label: "Email", value: user?.email }), _jsx(Row, { label: "Role", value: user?.role }), _jsx(Row, { label: "Company", value: user?.companyId ? `#${user.companyId}` : '—' })] })] }), _jsxs(Card, { children: [_jsx(CardHeader, { title: "Appearance", subtitle: "Pick a theme that suits you" }), _jsx(CardBody, { children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("div", { className: "text-sm font-medium", children: "Theme" }), _jsxs("div", { className: "text-xs text-subtle", children: ["Currently: ", theme] })] }), _jsxs("button", { onClick: toggle, className: "h-9 px-4 rounded-lg border border-border hover:bg-fg/[0.04] text-sm font-medium", children: ["Switch to ", theme === 'dark' ? 'light' : 'dark'] })] }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { title: "API access", subtitle: "Use these endpoints from any frontend" }), _jsxs(CardBody, { className: "text-sm space-y-1.5", children: [_jsx(Row, { label: "Swagger UI", value: _jsx("a", { className: "text-brand-600 dark:text-brand-400", href: "/swagger-ui.html", target: "_blank", children: "/swagger-ui.html" }) }), _jsx(Row, { label: "OpenAPI JSON", value: _jsx("a", { className: "text-brand-600 dark:text-brand-400", href: "/v3/api-docs", target: "_blank", children: "/v3/api-docs" }) }), _jsx(Row, { label: "Health", value: _jsx("a", { className: "text-brand-600 dark:text-brand-400", href: "/api/meta/health", target: "_blank", children: "/api/meta/health" }) })] })] })] }));
}
function Row({ label, value }) {
    return (_jsxs("div", { className: "flex justify-between border-b border-border last:border-0 py-2", children: [_jsx("span", { className: "text-subtle", children: label }), _jsx("span", { className: "font-medium", children: value || '—' })] }));
}
